//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.WebUi.service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductsService", Namespace="http://schemas.datacontract.org/2004/07/WebStore.Domain.DataContracts.Service")]
    [System.SerializableAttribute()]
    public partial class ProductsService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CountField;
        
        private int IdField;
        
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="service.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetListProducts", ReplyAction="http://tempuri.org/IService/GetListProductsResponse")]
        WebStore.WebUi.service.ProductsService[] GetListProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetListProducts", ReplyAction="http://tempuri.org/IService/GetListProductsResponse")]
        System.Threading.Tasks.Task<WebStore.WebUi.service.ProductsService[]> GetListProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetItemProduct", ReplyAction="http://tempuri.org/IService/GetItemProductResponse")]
        WebStore.WebUi.service.ProductsService GetItemProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetItemProduct", ReplyAction="http://tempuri.org/IService/GetItemProductResponse")]
        System.Threading.Tasks.Task<WebStore.WebUi.service.ProductsService> GetItemProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateProduct", ReplyAction="http://tempuri.org/IService/CreateProductResponse")]
        void CreateProduct(WebStore.WebUi.service.ProductsService item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateProduct", ReplyAction="http://tempuri.org/IService/CreateProductResponse")]
        System.Threading.Tasks.Task CreateProductAsync(WebStore.WebUi.service.ProductsService item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteProduct", ReplyAction="http://tempuri.org/IService/DeleteProductResponse")]
        void DeleteProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteProduct", ReplyAction="http://tempuri.org/IService/DeleteProductResponse")]
        System.Threading.Tasks.Task DeleteProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateProduct", ReplyAction="http://tempuri.org/IService/UpdateProductResponse")]
        void UpdateProduct(WebStore.WebUi.service.ProductsService item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateProduct", ReplyAction="http://tempuri.org/IService/UpdateProductResponse")]
        System.Threading.Tasks.Task UpdateProductAsync(WebStore.WebUi.service.ProductsService item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WebStore.WebUi.service.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WebStore.WebUi.service.IService>, WebStore.WebUi.service.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebStore.WebUi.service.ProductsService[] GetListProducts() {
            return base.Channel.GetListProducts();
        }
        
        public System.Threading.Tasks.Task<WebStore.WebUi.service.ProductsService[]> GetListProductsAsync() {
            return base.Channel.GetListProductsAsync();
        }
        
        public WebStore.WebUi.service.ProductsService GetItemProduct(int id) {
            return base.Channel.GetItemProduct(id);
        }
        
        public System.Threading.Tasks.Task<WebStore.WebUi.service.ProductsService> GetItemProductAsync(int id) {
            return base.Channel.GetItemProductAsync(id);
        }
        
        public void CreateProduct(WebStore.WebUi.service.ProductsService item) {
            base.Channel.CreateProduct(item);
        }
        
        public System.Threading.Tasks.Task CreateProductAsync(WebStore.WebUi.service.ProductsService item) {
            return base.Channel.CreateProductAsync(item);
        }
        
        public void DeleteProduct(int id) {
            base.Channel.DeleteProduct(id);
        }
        
        public System.Threading.Tasks.Task DeleteProductAsync(int id) {
            return base.Channel.DeleteProductAsync(id);
        }
        
        public void UpdateProduct(WebStore.WebUi.service.ProductsService item) {
            base.Channel.UpdateProduct(item);
        }
        
        public System.Threading.Tasks.Task UpdateProductAsync(WebStore.WebUi.service.ProductsService item) {
            return base.Channel.UpdateProductAsync(item);
        }
    }
}
